In [1]:
import pandas as pd

C:\Users\kumar_santhosh\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\kumar_santhosh\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
df = pd.read_csv('segmented_customers.csv')
print(df.head())

    Income  Recency  Customer_Days  Total_Spending  Total_Purchases  Clusters  \
0  58138.0       58           4951            1617               25       3.0
1  46344.0       38           4401              27                6       1.0
2  71613.0       26           4600             776               21       2.0
3  26646.0       26           4427              53                8       1.0
4  58293.0       94           4449             422               19       3.0

             Segment
0      Budget Buyers
1      New Customers
2  At Risk Customers
3      New Customers
4      Budget Buyers

In [3]:
recommendations = {
    "High Value Customers": {
        "Strategy": "Loyalty Rewards & Premium Offers",
        "Channels": ["Email", "Personal Calls"],
        "Offers": ["Exclusive Discounts", "Early Access"],
        "Goal": "Increase retention and lifetime value"},
    
    "New Customers": {
        "Strategy": "Welcome Campaign",
        "Channels": ["Email", "SMS"],
        "Offers": ["First Purchase Discount"],
        "Goal": "Convert into repeat customers"},
    
    "At Risk Customers": {
        "Strategy": "Re-engagement Campaign",
        "Channels": ["Email", "Push Notifications"],
        "Offers": ["Win-back Discounts"],
        "Goal": "Prevent churn"},
    
    "Budget Buyers": {
        "Strategy": "Price-Based Promotions",
        "Channels": ["SMS", "Ads"],
        "Offers": ["Coupons", "Seasonal Discounts"],
        "Goal": "Increase purchase frequency"}
}

In [4]:
df.rename(columns={'Clusters': 'Cluster'}, inplace=True)

In [5]:
def get_recommendation(segment):
    return recommendations.get(segment, "No recommendation available")

In [6]:
df['Recommendation'] = df['Segment'].apply(get_recommendation)

In [7]:
df.head()

,Income,Recency,Customer_Days,Total_Spending,Total_Purchases,Cluster,Segment,Recommendation
0,58138.0,58,4951,1617,25,3.0,Budget Buyers,"{'Strategy': 'Price-Based Promotions', 'Channe..."
1,46344.0,38,4401,27,6,1.0,New Customers,"{'Strategy': 'Welcome Campaign', 'Channels': [..."
2,71613.0,26,4600,776,21,2.0,At Risk Customers,"{'Strategy': 'Re-engagement Campaign', 'Channe..."
3,26646.0,26,4427,53,8,1.0,New Customers,"{'Strategy': 'Welcome Campaign', 'Channels': [..."
4,58293.0,94,4449,422,19,3.0,Budget Buyers,"{'Strategy': 'Price-Based Promotions', 'Channe..."

In [9]:
df['Strategy'] = df['Segment'].apply(
    lambda x: recommendations[x]['Strategy'] if x in recommendations else "Unknown")

df['Channels'] = df['Segment'].apply(
    lambda x: ", ".join(recommendations[x]['Channels']) if x in recommendations else "Unknown")

df['Offers'] = df['Segment'].apply(
    lambda x: ", ".join(recommendations[x]['Offers']) if x in recommendations else "Unknown")

df['Goal'] = df['Segment'].apply(
    lambda x: recommendations[x]['Goal'] if x in recommendations else "Unknown")

df.head()

,Income,Recency,Customer_Days,Total_Spending,Total_Purchases,Cluster,Segment,Recommendation,Strategy,Channels,Offers,Goal
0,58138.0,58,4951,1617,25,3.0,Budget Buyers,"{'Strategy': 'Price-Based Promotions', 'Channe...",Price-Based Promotions,"SMS, Ads","Coupons, Seasonal Discounts",Increase purchase frequency
1,46344.0,38,4401,27,6,1.0,New Customers,"{'Strategy': 'Welcome Campaign', 'Channels': [...",Welcome Campaign,"Email, SMS",First Purchase Discount,Convert into repeat customers
2,71613.0,26,4600,776,21,2.0,At Risk Customers,"{'Strategy': 'Re-engagement Campaign', 'Channe...",Re-engagement Campaign,"Email, Push Notifications",Win-back Discounts,Prevent churn
3,26646.0,26,4427,53,8,1.0,New Customers,"{'Strategy': 'Welcome Campaign', 'Channels': [...",Welcome Campaign,"Email, SMS",First Purchase Discount,Convert into repeat customers
4,58293.0,94,4449,422,19,3.0,Budget Buyers,"{'Strategy': 'Price-Based Promotions', 'Channe...",Price-Based Promotions,"SMS, Ads","Coupons, Seasonal Discounts",Increase purchase frequency

In [11]:
df[df['Strategy'] == "Unknown"]

,Income,Recency,Customer_Days,Total_Spending,Total_Purchases,Cluster,Segment,Recommendation,Strategy,Channels,Offers,Goal
2236,64014.0,56,4307,444,22,NaN,NaN,No recommendation available,Unknown,Unknown,Unknown,Unknown
2237,56981.0,91,4443,1241,19,NaN,NaN,No recommendation available,Unknown,Unknown,Unknown,Unknown
2238,69245.0,8,4444,843,23,NaN,NaN,No recommendation available,Unknown,Unknown,Unknown,Unknown
2239,52869.0,40,4910,172,11,NaN,NaN,No recommendation available,Unknown,Unknown,Unknown,Unknown

In [12]:
df.to_csv('Recommendation System.csv', index=False)